#!/bin/bash
echo "Enabling local dnsmasq DNS..."

sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved

sudo systemctl enable dnsmasq
sudo systemctl restart dnsmasq

sudo rm -f /etc/resolv.conf
echo "nameserver 127.0.0.1" | tee /etc/resolv.conf

dig reachme2.com @127.0.0.1
ping -c 2 sel2in.com

